// import { SessionProvider } from "next-auth/react";

import { Navigation } from "./components/navbar/Navigation";
import "./globals.css";

export const metadata = {
  title: "마음 처방전",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    // <SessionProvider session={pageProps.session}>
    <html lang="en">
      <body>
        <header>
          <Navigation />
        </header>
        <main>{children}</main>
      </body>
    </html>
    // </SessionProvider>
  );
}
