import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "마음 처방전",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav className="nav-wrapper">
            <Link href="/" className="home">
              마음 처방전
            </Link>
            <ul className="menu">
              <Link href="/public-board">
                <li>공유게시판</li>
              </Link>
              <Link href="/recommend-board">
                <li>추천게시판</li>
              </Link>
              <Link href="/mypage">
                <li>마이페이지</li>
              </Link>
            </ul>
          </nav>
        </header>
        <main>
          {/* page.js들어가는 부분이 아래 children */}
          {children}
        </main>
      </body>
    </html>
  );
}
